apiVersion: v1
kind: Service
metadata:
  name: k8s-java
  namespace: default
  labels:
    app: k8s-java
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30090 #service对外开放端口
  selector:
    app: k8s-java
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: k8s-java #名称
  labels:
    app: k8s-java #标注
spec:
  replicas: 3 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: k8s-java
  template:
    metadata:
      labels:
        app: k8s-java
    spec:
      containers: #docker容器的配置
        - name: k8s-java
          image: registry.cn-hangzhou.aliyuncs.com/easonsu/k8s-java:0.0.1-SNAPSHOT # pull镜像的地址 ip:prot/dir/images:tag
          imagePullPolicy: IfNotPresent #pull镜像时机，
          ports:
            - containerPort: 8080 #容器对外开放端口
